# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDimensionTable',
            fields=[
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('state_code', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('no_of_funding_rounds', models.IntegerField(blank=True, null=True)),
                ('total_funding_received', models.TextField(blank=True, null=True)),
                ('founded_date', models.TextField(blank=True, null=True)),
                ('employee_count', models.TextField(blank=True, null=True)),
                ('mgmt_01', models.TextField(blank=True, null=True)),
                ('mgmt_02', models.TextField(blank=True, null=True)),
                ('mgmt_03', models.TextField(blank=True, null=True)),
                ('mgmt_04', models.TextField(blank=True, null=True)),
                ('mgmt_05', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_dimension_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundingRoundDimension',
            fields=[
                ('funding_round_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=50)),
                ('round_type', models.TextField(blank=True, null=True)),
                ('lead_investor_id', models.CharField(max_length=50)),
                ('other_investor_1', models.TextField(blank=True, null=True)),
                ('other_investor_2', models.TextField(blank=True, null=True)),
                ('other_investor_3', models.TextField(blank=True, null=True)),
                ('other_investor_4', models.TextField(blank=True, null=True)),
                ('other_investor_5', models.TextField(blank=True, null=True)),
                ('other_investor_6', models.TextField(blank=True, null=True)),
                ('other_investor_7', models.TextField(blank=True, null=True)),
                ('other_investor_8', models.TextField(blank=True, null=True)),
                ('other_investor_9', models.TextField(blank=True, null=True)),
                ('other_investor_10', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funding_round_dimension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorsDimensionsTableFinal',
            fields=[
                ('investor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('investor_name', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('state_code', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('founded_date', models.TextField(blank=True, null=True)),
                ('investor_type', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('investment_count', models.IntegerField(blank=True, null=True)),
                ('total_funding_usd', models.TextField(blank=True, null=True)),
                ('mgmt_01', models.TextField(blank=True, null=True)),
                ('mgmt_02', models.TextField(blank=True, null=True)),
                ('mgmt_03', models.TextField(blank=True, null=True)),
                ('mgmt_04', models.TextField(blank=True, null=True)),
                ('mgmt_05', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investors_dimensions_table_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeDimensionTable',
            fields=[
                ('date_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('day', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_dimension_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
                ('industry', models.TextField(max_length=200, null=True)),
                ('org_name', models.TextField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundingFactTable',
            fields=[
                ('funding_round_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='venturetrends.FundingRoundDimension')),
                ('amount_raised', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funding_fact_table',
                'managed': False,
            },
        ),
    ]
