# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venturetrends', '0002_auto_20180424_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
