# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturetrends', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_pk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
